### ISSUE TITLE
ecs cli doesn't work on an ec2 instance without an IAM role - Panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tumapath** [aws/amazon-ecs-cli#105]
I have an jenkins box configured in our aws console to run our ecs tasks. The jenkins ec2 instance doesn't have IAM role configured as its primary purpose to trigger the ecs tasks. I am passing the aws credentials via jenkins params for ecs but the ecs cli fails while trying to retrieve the metadata.

I would assume if we could defer the error message this issue will be resolved.

The command used : 
ecs-cli compose --project-name members-es --file members-es.yml service up
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x6e9b05]

goroutine 1 [running]:
github.com/aws/aws-sdk-go/aws/ec2metadata.(*EC2Metadata).GetMetadata(0x0, 0xad3770, 0x19, 0x0, 0x0, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/src/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go:24 +0x1b5
github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds.requestCredList(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/src/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go:133 +0x85

Any short term workaround will be greatly appreciated.

**Comment by rakeshrc** [comment]
Is there any workaround for this. we see ecs-cli compose failing with this error

**Comment by markriggins** [comment]
Any work around ?   We're running into this also

**Comment by markriggins** [comment]
Looking into the source code, I found a fix and a hint.

The fix  add these 3 lines to the beginngin of requestCredList in ec2_role_provider.go

```
// requestCredList requests a list of credentials from the EC2 service.
// If there are no credentials, or there is an error making or receiving the request
func requestCredList(client *ec2metadata.EC2Metadata) ([]string, error) {
	if client == nil {
		return nil, awserr.New("EC2RoleRequestError", "no Client ", nil)
	}

```

But that just gets you to an esoteric error message: 

> Unable to create an instance of ECSParams given the cli context" error="NoCredentialProviders: no valid providers in chain. Deprecated. \n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors" 

Which (as far as I can determine) relates to this: http://stackoverflow.com/questions/34582908/error-registering-nocredentialproviders-no-valid-providers-in-chain-ecs-agent

To which we responded by
1) configuring Jenkins to use its own IAM role, instead of an EC2 Role.
2) set `aws_profile: default` in the .ecs/config file

Then after adding some permissions to the Jenkins role, got us building again.

Which sadly means that a Y release of ecs-cli broke our `ability to deploy software`

AMAZON ARE YOU LISTENING?

**Comment by uttarasridhar** [comment]
Thanks for reporting the bug and apologies for the delay in the fix.
Released in https://github.com/aws/amazon-ecs-cli/releases/tag/v0.3.1
