### ISSUE TITLE
describe-clusters without arguments should describe all clusters, not the default cluster.

### ISSUE THREAD

**Issue by nrh** [aws/amazon-ecs-cli#1067]
#### Summary
`aws ecs describe-clusters` should describe all extant clusters.

#### Description
`aws ecs describe-clusters` behavior is a bit confusing.  coming from ec2, where `aws ec2 describe-instances` lists all extant instances in the region, I would expect `aws ecs describe-clusters` to behave similarly.

version: `aws-cli/2.0.19 Python/3.8.3 Darwin/19.5.0 botocore/2.0.0dev23`
go version: go version go1.14.3 darwin/amd64
os: Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

#### Expected Behavior

`aws ecs describe-clusters` describes all clusters in the region, mirroring aws ec2 cli behavior.

#### Observed Behavior
`aws ecs describe-clusters` with no arguments attempts to describe only the default cluster, and returns an error when the default cluster doesn't exist.

**Comment by iamhopaul123** [comment]
Hi nrh,

Thank you for your feedback on `aws ecs describe-clusters`. ECS’s recommendation currently is to call `list-clusters` to get all the existing clusters and use `describe-clusters` to describe some of them. This approach offers a bounded call for our API, which is intentional.

Additionally, The ECS CLI is actually pretty different than the AWS CLI. The AWS CLI is a great way to call ECS APIs, but ECS-CLI focuses more on setting up resources (ECS service, monitor deployments), converting docker-compose files, replicating your services locally, etc. If you have more questions about AWS CLI behaviors for ECS, maybe you can cut the issue in our ECS [roadmap](https://github.com/aws/containers-roadmap/issues). Thank you!
