### ISSUE TITLE
compose create randomly fails to create task definition

### ISSUE THREAD

**Issue by flah00** [aws/amazon-ecs-cli#130]
```
$ ecs-cli --version
ecs-cli version 0.4.0 (*UNKNOWN)
```

I created a [docker-compose.yml](https://gist.github.com/flah00/6df5eb89f5addfc348724373f80add20#file-docker-compose-yml) and I've been trying to use it with `ecs-cli compose create`. I've had very mixed results. More often than not, at least one of the `Image` keys turns up null, during the ecs-cli conversion, ie [this error](https://gist.github.com/flah00/6df5eb89f5addfc348724373f80add20#file-missing_image_key_error-log). One out of ten times, the task is [successfully](https://gist.github.com/flah00/6df5eb89f5addfc348724373f80add20#file-success-log) created.

**Comment by flah00** [comment]
I'm finding the same results with 0.4.1.

**Comment by uttarasridhar** [comment]
Looking at the docker-compose.yml file that you use, you have both build and image options mentioned. As of v0.4.1, ecs-cli does not support build option. You can look [here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose.html) for a list of supported options.

As for why task was successfully created sometimes is because of the following:
- We use libcompose to parse compose yaml.
- With v1 file format: "Using build together with image is not allowed. Attempting to do so results in an error." is referenced from [compose docs](https://docs.docker.com/compose/compose-file/#/build ). And libcompose still allows either build or image option, not both. [See here](https://github.com/docker/libcompose/blob/master/config/merge.go#L144)
- During the parsing, if build option was processed first, image key was deleted. This is when ecs doesn't find the image and sets to null. Hence the error. (The reverse case is when it succeeds)

My recommendation is to remove the build option from the yml file for now, because ecs-cli doesn't support it today.

**Comment by flah00** [comment]
Thanks for the quick response. It seems like the `build` key was the problem. I'm able to consistently create task definitions now.
