### ISSUE TITLE
forward devices to docker

### ISSUE THREAD

**Issue by jas99** [aws/amazon-ecs-cli#18]
Can I forward gpu devices to docker with compose file. The option is not thr in UI. Any comments on this will be appreciated.

Thx

**Comment by jas99** [comment]
@kiranmeduri @mndoci  @sentientmonkey  @hyandell  @santtu 

Relppp!!!!!! :p

**Comment by euank** [comment]
You cannot currently use something like the `--devices` flag, but I've made sure this is tracked as a feature request internally.

By using the privileged flag (not in compose, see #22) most devices will be passed through, but this isn't necessarily an acceptable tradeoff.

Since this is an ECS issue more than a cli issue and we're already tracking that feature request internally, I'm closing this.

Best,
Euan
