### ISSUE TITLE
volumes broken?

### ISSUE THREAD

**Issue by psineur** [aws/amazon-ecs-cli#181]
Looks like volumes should support paths (at least judging by people responses to #11).
However when I try to `ecs-cli compose up` containers are stopped after pending for a bit and then I can see this in the stopped task error:

## CannotCreateContainerError: API error (500): create ./volumes/nginx.conf: "./volumes/nginx.conf" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed

Any workarounds?

**Comment by dsifford** [comment]
Having the same issue here.... Is this repo actively being maintained?

**Comment by uttarasridhar** [comment]
The host path for the volume cannot be relative, which is why the compose up is failing (`./volumes/nginx.conf` is a relative path). This is enforced by the docker daemon itself, which is why you’re getting the 500 error from the daemon. You can try changing it to `/volumes/nginx.conf`.

Thanks for reporting this. We will add better validations to our APIs.

Feel free to reopen this if you continue to face the issue.

**Comment by psineur** [comment]
I guess ideally, I would like to see this issue being closed at least by commit, that changes the error message to something like "... Make sure to use absolute paths, relative paths are unsupported".
