### ISSUE TITLE
Remove compose default prefix (backward incompatible)

### ISSUE THREAD

**Issue by yinshiua** [aws/amazon-ecs-cli#239]
`ecs-cli compose up` and `ecs-cli compose service  up` appends a prefix (`ecscompose-` and `ecscompose-service-`) to the task definition name and service name. There were many complains about the added prefixes previously (issues: https://github.com/aws/amazon-ecs-cli/issues/51, https://github.com/aws/amazon-ecs-cli/issues/82, https://github.com/aws/amazon-ecs-cli/issues/91, https://github.com/aws/amazon-ecs-cli/issues/97), so we made the prefixes configurable in the config file. I would like to remove the prefixes completely from the config file and not append the prefix at all. This will be a backward incompatible change, so we would like your opinion on this.

The prefix is currently stored in `~/.ecs/config`.

**Comment by samuelkarp** [comment]
Would removing the prefix mean that `ecs-cli` could no longer manage existing clusters and services it launched when you upgrade it?

**Comment by yinshiua** [comment]
For clusters, we are using the default cfn default prefix, so if you did not customize the cfn prefix, you can continue to manage existing clusters.

For services, you can add the prefix to the project name (ex. `ecs-cli compose --project-name "ecscompose-service-<project_dir>" service scale`) to manage existing services

**Comment by samuelkarp** [comment]
I think the backwards incompatibility here is going to cause pain for people unexpectedly.  If we're switching the default, there should be fallback logic to handle services that were created prior to this change.

**Comment by etsuo** [comment]
@yinshiua this is actually causing a problem for us. We just upgraded our `ecs-cli` and now we're getting an `ecscompose` prefix on our task definitions... our scripts share a bunch of different deployments for different clients, so I'm not sure that the `.ecs` config file is really ideal for us. Is there any way to turn off this prefixing or to pass in an alternative prefix as an argument rather than having yet another magic config file that my ops team and developers have to remember to configure? thanks
