### ISSUE TITLE
service up command times out

### ISSUE THREAD

**Issue by chintans** [aws/amazon-ecs-cli#257]
I am trying to use ecs-cli to update the service. I was suggested in one of the previous issue that service up also updates container. I changed my CI builds to use this command. as it turns out ecs command times out after running for almost 10 min. When I check in AWS console. It shows services are running and updated.

I am using the latest version of tool 0.5.0. It times out on ubuntu trusty (x64).

**Comment by yinshiua** [comment]
@chintans  Did the CLI timed out on Describe ECS Service status?
If so, this is because the tasks that are running is not using the latest service configuration. When you update a service, ECS will try to update the service by spinning up another task, and kill the existing task. To better troubleshoot this, you can go to AWS Console, click into your service, and look at the **Events** tab.

**Comment by yinshiua** [comment]
Closing this since no response in 7 days. Feel free to reopen this.

**Comment by khaliqgant** [comment]
I was also running into a similar issue and figured I should share my resolution. I had to configure the cluster to get the service to update. I suspect it was timing out because the service I was attempting to update wasn't found within the cluster because it hadn't been configured.

```
ecs-cli configure --cluster $(AWS_CLUSTER) --profile $(AWS_PROFILE)
```
Then running service up fixed the timeout issue for me.
