### ISSUE TITLE
Delete tasks

### ISSUE THREAD

**Issue by bee-keeper** [aws/amazon-ecs-cli#332]
Hi, 

From the looks of it, it seems we can't delete tasks with ecs-cli - please could you confirm this is the case or not.

Thanks,

**Comment by PettitWesley** [comment]
Hey @bee-keeper, so ECS only allows you to stop tasks. After a task has been stopped, it can still be described using the [describe-tasks](http://docs.aws.amazon.com/cli/latest/reference/ecs/describe-tasks.html) API for a short period of time after it has been stopped. However, it will eventually be "deleted", there is just no API call which allows you to immediately delete the Task. There are multiple reasons for this, but one is that we want stopped tasks to be visible for some time after they are stopped so that customers can clearly see that the task has been stopped, and to allow them to get any error messages associated with the stopped task (to facilitate debugging).

**Comment by bee-keeper** [comment]
Thanks for taking the time to answer, that clears things up.
