### ISSUE TITLE
Scale cluster to 0

### ISSUE THREAD

**Issue by bee-keeper** [aws/amazon-ecs-cli#335]
Hi there,

It doesn't seem possible to scale a cluster to 0, ie remove all attached ec2 instances.  Is this by design?

```
ecs-cli scale --size 0 --cluster my-cluster --capability-iam
INFO[0001] Waiting for your cluster resources to be updated... 
INFO[0002] Cloudformation stack status                   stackStatus="UPDATE_IN_PROGRESS"
ERRO[0064] Failure event                                 reason= resourceType="AWS::CloudFormation::Stack"
ERRO[0064] Error executing 'scale': Cloudformation failure waiting for 'UPDATE_COMPLETE'. State is 'UPDATE_ROLLBACK_COMPLETE' 
```
In my current workflow this is something which would be very useful as we bring up a cluster to process a finite number of jobs on a queue.  Having to recreate the cluster each time seems redundant and it would be much easier to just scale it up and down.

**Comment by SoManyHs** [comment]
Hi @bee-keeper,

Thanks for bringing this to our attention. I was able to reproduce this issue and it would appear to be due to the fact that the Cloud Formation stack that we use to create your cluster creates an AutoScaling Group with a MinSize of 1 instance.  We've fixed this in #336.

In the meantime, until we release this fix, we recommend updating your Cloud Formation Template in the AWS console to manually set the MinField to 0 in order to enable the `ecs-cli scale` command to work with `--size 0`. Please let us know if you have any further issues.
