### ISSUE TITLE
Service not getting created without Load Balancer

### ISSUE THREAD

**Issue by sumitsarkar** [aws/amazon-ecs-cli#359]
I called `ecs-cli compose --cluster cluster-name service up --role ecsServiceRole`  and it throws the error:

```
level=fatal msg="InvalidParameterException: Container Name can not be blank.\n\tstatus code: 400, request id:
```
I do not want to run the service with a load balancer or a target group. Is it not possible to create a service without a load balancer or target-group?

**Comment by SoManyHs** [comment]
Hi @sumitsarkar,

Thanks for submitting your issue. The compose service up command should allow you to create a service without a load balancer. Could you include your `docker-compose.yml` and `ecs-params.yml` (if you have one) files?

**Comment by SoManyHs** [comment]
Hi @sumitsarkar, are you still experiencing this issue?

**Comment by sumitsarkar** [comment]
@SoManyHs I am sorry about the delayed response. I started using aws-cli instead of the ecs-cli for the deployment scripts. I can give it one more shot and let you know the results.

**Comment by xinyifly** [comment]
I'm having the same problem, but it occurs when I try to specify a load balancer.

```
+ ecs-cli compose -f user-api.yml service up
time="2017-12-26T10:52:14+08:00" level=warning msg="Skipping unsupported YAML option..." option name=networks 
time="2017-12-26T10:52:14+08:00" level=warning msg="Skipping unsupported YAML option for service..." option name=extends service name=user-api 
time="2017-12-26T10:52:14+08:00" level=warning msg="Skipping unsupported YAML option for service..." option name=networks service name=user-api 
time="2017-12-26T10:52:15+08:00" level=info msg="Using ECS task definition" TaskDefinition="ecscompose-user-api:123" 
time="2017-12-26T10:52:15+08:00" level=info msg="Created an ECS service" service=ecscompose-service-user-api taskDefinition="ecscompose-user-api:123" 
time="2017-12-26T10:52:15+08:00" level=info msg="Updated ECS service successfully" desiredCount=1 serviceName=ecscompose-service-user-api 
time="2017-12-26T10:52:31+08:00" level=info msg="(service ecscompose-service-user-api) has started 1 tasks: (task 23f024b9-735e-462d-9ddb-b6b3391b28e3)." timestamp=2017-12-26 02:52:16 +0000 UTC 
time="2017-12-26T10:53:01+08:00" level=info msg="Service status" desiredCount=1 runningCount=1 serviceName=ecscompose-service-user-api 
time="2017-12-26T10:53:01+08:00" level=info msg="(service ecscompose-service-user-api) has reached a steady state." timestamp=2017-12-26 02:52:58 +0000 UTC 
time="2017-12-26T10:53:01+08:00" level=info msg="ECS Service has reached a stable state" desiredCount=1 runningCount=1 serviceName=ecscompose-service-user-api 
```

```
+ ecs-cli compose -f user-api.yml service up --load-balancer-name green-stage-user-api
time="2017-12-26T10:54:44+08:00" level=warning msg="Skipping unsupported YAML option..." option name=networks 
time="2017-12-26T10:54:44+08:00" level=warning msg="Skipping unsupported YAML option for service..." option name=extends service name=user-api 
time="2017-12-26T10:54:44+08:00" level=warning msg="Skipping unsupported YAML option for service..." option name=networks service name=user-api 
time="2017-12-26T10:54:46+08:00" level=info msg="Using ECS task definition" TaskDefinition="ecscompose-user-api:123" 
time="2017-12-26T10:54:46+08:00" level=error msg="Error creating service" error="InvalidParameterException: Container Name can not be blank.\n\tstatus code: 400, request id: 216c00c3-e9e8-11e7-bb26-d5c57db262ce" service=ecscompose-service-user-api 
time="2017-12-26T10:54:46+08:00" level=fatal msg="InvalidParameterException: Container Name can not be blank.\n\tstatus code: 400, request id: 216c00c3-e9e8-11e7-bb26-d5c57db262ce" 
```

**Comment by h-bragg** [comment]
I had the same issue as the original comment. 

After some head scratching i found this bit: 

If you specify a role: `--role` you then have to specify a load balancer.

> ```
>   --role value    [Optional] Specifies the name or full Amazon Resource Name (ARN)
>                   of the IAM role that allows Amazon ECS to make calls to your load balancer or target
>                   group on your behalf. This parameter is required if you are using a load balancer or
>                   target group with your service. If you specify the role parameter, you must also specify
>                   a load balancer name or target group ARN, along with a container name and container
>                   port.
> ```

Perhaps a different error message would be more useful here.

**Comment by jicowan** [comment]
The esc-cli will not create a service behind a load-balancer.  See the following examples: 
```
ecs-cli compose service up --deployment-max-percent 100 --deployment-min-healthy-percent 0 --target-group-arn arn:aws:elasticloadbalancing:us-east-1:820537372947:targetgroup/service-b-tg/3a30e651d497781a --launch-type FARGATE

WARN[0000] Skipping unsupported YAML option...           option name=networks
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=service-a
WARN[0000] Environment variable is unresolved. Setting it to a blank value...  key name="AWS_XRAY_DAEMON_ADDRESS"
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=x-ray
WARN[0000] Environment variable is unresolved. Setting it to a blank value...  key name="AWS_XRAY_DAEMON_ADDRESS"
INFO[0000] Using ECS task definition                     TaskDefinition="service-b:3"
ERRO[0000] Error creating service                        error="InvalidParameterException: Container Name can not be blank.\n\tstatus code: 400, request id: 27df86b4-2882-11e8-b0a5-ff68f05b2b7f" service=service-b
FATA[0000] InvalidParameterException: Container Name can not be blank.
status code: 400, request id: 27df86b4-2882-11e8-b0a5-ff68f05b2b7f

ecs-cli compose --project-name service-b-project --file docker-compose.yml service up --target-group-arn arn:aws:elasticloadbalancing:us-east-1:820537372947:targetgroup/service-b-tg/3a30e651d497781a

WARN[0000] Skipping unsupported YAML option...           option name=networks
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=service-a
WARN[0000] Environment variable is unresolved. Setting it to a blank value...  key name="AWS_XRAY_DAEMON_ADDRESS"
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=x-ray
WARN[0000] Environment variable is unresolved. Setting it to a blank value...  key name="AWS_XRAY_DAEMON_ADDRESS"
INFO[0000] Using ECS task definition                     TaskDefinition="service-b-project:2"
ERRO[0000] Error creating service                        error="InvalidParameterException: Container Name can not be blank.\n\tstatus code: 400, request id: 239c9011-2883-11e8-80d1-895162b77017" service=service-b-project
FATA[0000] InvalidParameterException: Container Name can not be blank.
status code: 400, request id: 239c9011-2883-11e8-80d1-895162b77017

ecs-cli compose service up --load-balancer-name service-b-lb --container-name xxxx --container-port 8080

WARN[0000] Skipping unsupported YAML option...           option name=networks
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=service-a
WARN[0000] Environment variable is unresolved. Setting it to a blank value...  key name="AWS_XRAY_DAEMON_ADDRESS"
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=x-ray
WARN[0000] Environment variable is unresolved. Setting it to a blank value...  key name="AWS_XRAY_DAEMON_ADDRESS"
INFO[0000] Using ECS task definition                     TaskDefinition="service-b:3"
ERRO[0000] Error creating service                        error="InvalidParameterException: Classic Load Balancers are not supported with Fargate.\n\tstatus code: 400, request id: 047ef2df-2885-11e8-b651-0323201b449e" service=service-b
FATA[0000] InvalidParameterException: Classic Load Balancers are not supported with Fargate.
status code: 400, request id: 047ef2df-2885-11e8-b651-0323201b449e
```

The load balancer I specified is a ALB, not an ELB.

**Comment by jicowan** [comment]
I think I realized my mistake, you **have** to specify the --target-group-arn when your service is fronted by an ALB.  You **do not** need to specify port or container so long as you specify the target-group-arn.

**Comment by SoManyHs** [comment]
HI @jicowan,
Apologies for the delayed response -- sounds like you were able to get your service launched successfully. You can also check out [this comment](https://github.com/aws/amazon-ecs-cli/issues/426#issuecomment-367843422) from a previous issue, but we apologize that this was so confusing. If you have suggestions on what you feel would have made this easier for you, feel free to open an issue or let us know here!

**Comment by jicowan** [comment]
Hi @SoManyHs, I'm not sure why I got 2 different responses using the same syntax.  In my opinion, this should not have produced an error: 

```
ecs-cli compose service up --deployment-max-percent 100 --deployment-min-healthy-percent 0 --target-group-arn arn:aws:elasticloadbalancing:us-east-1:820537372947:targetgroup/service-b-tg/3a30e651d497781a --launch-type FARGATE

WARN[0000] Skipping unsupported YAML option...           option name=networks
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=service-a
WARN[0000] Environment variable is unresolved. Setting it to a blank value...  key name="AWS_XRAY_DAEMON_ADDRESS"
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=x-ray
WARN[0000] Environment variable is unresolved. Setting it to a blank value...  key name="AWS_XRAY_DAEMON_ADDRESS"
INFO[0000] Using ECS task definition                     TaskDefinition="service-b:3"
ERRO[0000] Error creating service                        error="InvalidParameterException: Container Name can not be blank.\n\tstatus code: 400, request id: 27df86b4-2882-11e8-b0a5-ff68f05b2b7f" service=service-b
FATA[0000] InvalidParameterException: Container Name can not be blank.
status code: 400, request id: 27df86b4-2882-11e8-b0a5-ff68f05b2b7f
```

**Comment by lferro9000** [comment]
If you have a container that doesn't expose any port, you are forced to use --container-port anyway:
```
ecs-cli compose -f ecs-deploy.yml --project-name test-service service up --container-name test-service-container --aws-profile theprofile -c thecluster -r theregion
```
You get an error of:

"Container Port is missing"

When you add a container port as "--container-port 80" (which is not needed for the container to work as it doesn't need to be reacheable by anything), it will generate nevertheless the next error:

"Load Balancer Name can not be blank"

And the documentation explicitly states that a Load Balancer is optional.

**Comment by CrackHD** [comment]
@jicowan Maybe you can show how, using `ecs-cli compose`, we can deploy a load-balanced _FARGATE_ app? instead of providing snippets that intentionally do not work..

**Comment by CrackHD** [comment]
@jicowan Maybe you can show how, using `ecs-cli compose`, we can deploy a **load-balanced _FARGATE_** app so it will have a sticky-static public IP? 
The best i am thinking about is if i only had to change `ecs-params.yml` for that somehow.

For ecs_network_mode: awsvpc .

Instead of providing snippets that intentionally do not work..

There is no snippet for this in AWS docs. The closest i've found is non-cli instruction https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_GetStarted.html#first-run-service which has no use for me. I actually found ECS Console very frustrating compared to AWS Beanstalk in terms of load balancer creation and management. 

The fact that my app works and frequently changes its IP and there is actually no point in button "add more like this" in ECS console since they will get same randomizing IPs, just drives me crazy. I don't know which is worse this or the fact that ecs-cli related docs has no mention of anything except `assign_public_ip`..

**Comment by CrackHD** [comment]
@jicowan Maybe you can show how, using `ecs-cli compose`, we can deploy a **load-balanced _FARGATE_** app so it will have a sticky-static public IP? 
The best i am thinking about is if i only had to change `ecs-params.yml` for that somehow.

For ecs_network_mode: awsvpc .

There is no snippet for this in AWS docs. The closest i've found is non-cli instruction https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_GetStarted.html#first-run-service which has no use for me. I actually found ECS Console very frustrating compared to AWS Beanstalk in terms of load balancer creation and management. 

The fact that my app works and frequently changes its IP and there is actually no point in button "add more like this" in ECS console since they will get same randomizing IPs, just drives me crazy. I don't know which is worse this or the fact that ecs-cli related docs has no mention of anything except `assign_public_ip`..

**Comment by jicowan** [comment]
@CrackHD I am not using the ecs-cli to provision a load balancer.  I'm using it to wire my service to an existing load balancer.  If you're looking for a CLI that can do both, have a look at the Fargate CLI, https://github.com/jpignata/fargate.

**Comment by CrackHD** [comment]
I did not see your answer so i deleted my original comment to this thread as it was a bit off topic and I somehow find a solution shortly, without really being sure it will work before trying.

The original question was: **How to create load-balanced Fargate service with ecs-cli?**

And the solution is simple.

You have to create Network Load Balancer with new target group with target type "ip" and assign  proper availability zone, VPC and security group, for me security group was equal to ECS service security group as service only serves port 80.

Then you have to copy ARN identifier of the created target group for that balancer and use it to create your service:
```sh
    ecs-cli compose service create \
       --target-group-arn "$ARN" \
       --container-name nginx \
       --container-port 80
```

The original snippet comes from AWS docs, although, as i initially pointed out, AWS docs does not really cover load balancing topic with ECS. 
Strangely, since ECS is very easy tool exactly to create balanced deployments.

**Comment by CrackHD** [comment]
I did not see your answer so I deleted my original comment to this thread since it was a bit off topic and I somehow find a solution shortly, without really being sure it will work before trying.

The original question was: **How to create load-balanced Fargate service with ecs-cli?**

And the solution is simple.

You have to create Network Load Balancer with new target group with target type "ip" and assign  proper availability zone, VPC and security group, for me security group was equal to ECS service security group as service only serves port 80.

Then you have to copy ARN identifier of the created target group for that balancer and use it to create your service:
```sh
    ecs-cli compose service create \
       --target-group-arn "$ARN" \
       --container-name nginx \
       --container-port 80
```

The original snippet comes from AWS docs, although, as i initially pointed out, AWS docs does not really cover load balancing topic with ECS. 
Strangely, since ECS is very easy tool exactly to create balanced deployments.

**Comment by sumitsarkar** [comment]
Sorry for the radio silence. But I think I remember what the problem was when I last used ecs-cli. I had created a service with a load balancer and target group. But with the next `compose up` I tried to create the service without the target group and load balancer. This is not allowed in AWS (Please correct me if I am wrong). 

So, the service needs to be deleted and  a new service without the target group and load balancer needs to be created. If ECS CLI could automate this process, that'd be great.

**Comment by SoManyHs** [comment]
Hi @sumitsarkar,

Correct, a service cannot be updated with changes in the loadbalancer configuration. In other words, if a service was created with or without a loadbalancer, you cannot remove or add it on a running service unless you re-create it.

@jicowan I've put up a PR (#640) to clarify the flag usage for associating a load balancer with a service -- feel free to provide any feedback on how to make this clearer!

@CrackHD The [AWS docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-load-balancing.html) have some guidance on Service Load Balancing with ECS, as well as this [walk-through](https://medium.com/containers-on-aws/using-aws-application-load-balancer-and-network-load-balancer-with-ec2-container-service-d0cb0b1d5ae5) written by @nathanpeck. 

Finally, we are also working on some new tooling to simplify the creation of resources such as a load-balanced Fargate resources via the [AWS CDK](https://github.com/awslabs/aws-cdk), which is currently in a beta release. Feel free to check out the specific construct for a publicly load-balanced Fargate service [here](https://github.com/SoManyHs/aws-cdk/blob/ecs-demo/packages/%40aws-cdk/aws-ecs/lib/load-balanced-fargate-service.ts).

Let me know if that helps!

**Comment by ambsw-technology** [comment]
Sorry to ping an old issue, but this (and really only this) ranks very highly on Google and the same message can occur for a CloudFormation template.  It's confusing that the error doesn't specify that the issue is related to the `LoadBalancer`, but similar to other comments here I found that I needed both a `ContainerName` and `ContainerPort` (with `TargetGroupArn`).

**Comment by Zeka13** [comment]
@ambsw-technology whats the question ?

**Comment by ambsw-technology** [comment]
@Zeka13 Not a question.  Reiterating the aspect of the CLI resolution that also works for CloudFormation.
