### ISSUE TITLE
auto scaling groups starts outdated agent

### ISSUE THREAD

**Issue by exp0nge** [aws/amazon-ecs-cli#371]
Instances created from a auto scale group has outdated agents and I have to manually go in and update them

**Comment by PettitWesley** [comment]
@exp0nge thanks for your question. Since I'm not sure when you created your cluster, or which version of the ECS CLI you are using, my answer has two parts. 

##### Why Does the `ecs-cli up` command currently launch instances with an outdated version of the ECS Agent?

- Each version of the ECS CLI that is released contains the latest ECS Optimized AMI IDs in the code for use in our CloudFormation template. Consequently, we recommend always upgrading to the newest version of the ECS CLI, to ensure that you will have the latest AMIs. In the future, we would like to move away from requiring upgrading the ECS CLI to use the latest AMIs; however, at this time upgrading is required. 
- However, latest release of the ECS CLI (v1.0.0) is not using the AMI with the latest version of the Agent. This is due to issues discovered in the latest version of the agent: https://github.com/aws/amazon-ecs-agent/issues/1063#issuecomment-343335160. 

##### Why does my existing cluster continue to spawn instances with an outdated agent?

- When a cluster is created with `ecs-cli up`, the AMI ID is added as a parameter in the CloudFormation template for that cluster. Consequently, new instances in that cluster will continue to use the same version of the agent, even if its outdated. However, you can update the CloudFormation Template in the CloudFormation Console to use the latest AMI ID for your AWS Region. The latest AMI IDs can be found here: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html

I'm going to mark this as a question, and a feature request. I think the feature request has two parts:
1. Automatically update the AMI ID in the ECS CLI without requiring upgrading to the latest version of the ECS CLI.
2. Add a feature in the ECS CLI to update/upgrade an existing CloudFormation stack, so that users don't have to do this manually. 

Let me know if you have any more questions or feedback!

**Comment by exp0nge** [comment]
I actually had to change the launch configuration to change the AMI.

**Comment by PettitWesley** [comment]
@exp0nge This has been fixed; as of ECS CLI `v1.5.0`, the Image ID is obtained using [ECS AMI Metadata in SSM Parameter Store](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/retrieve-ecs-optimized_AMI.html).
