### ISSUE TITLE
Keypair error while deploying a cluster

### ISSUE THREAD

**Issue by brainst0rm** [aws/amazon-ecs-cli#466]
### Summary
I get this error while using "up" to deploy the cluster which says the keypair does not exist. I've gone through a few topics with same issue but i dont see an option to choose the region anywhere.

Also, I've tried creating a new key pair but that didn't help either.

### Observed Behavior
INFO[0004] Created cluster                               cluster=stack region=us-west-2
INFO[0004] Waiting for your CloudFormation stack resources to be deleted...
INFO[0005] Cloudformation stack status                   stackStatus=DELETE_IN_PROGRESS
INFO[0041] Waiting for your cluster resources to be created...
INFO[0042] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
INFO[0109] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
INFO[0172] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
ERRO[0206] Failure event                                 reason="The key pair 'test.pem' does not exist" resourceType="AWS::AutoScaling::LaunchConfiguration"
FATA[0206] Error executing 'up': Cloudformation failure waiting for 'CREATE_COMPLETE'. State is 'ROLLBACK_IN_PROGRESS'

**Comment by SoManyHs** [comment]
Hi @brainst0rm,

Can you include the exact command you ran that produced that error?

My guess is you're likely passing in the wrong keypair name ("test.pem") to your command, instead of just "test". You can verify the name of your keypairs by running:
`~/ecs/ecs-cli/testing/projects/test_fields$ aws ec2 describe-key-pairs --region us-west-2`

You should get something like:
```
{
    "KeyPairs": [
        {
            "KeyName": "test", 
            "KeyFingerprint": "xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:5d:33:a5:90:3f:9e:3e:11:ab:b9"
        }
    ]
}
```

You can then pass keypair name into the ecs-cli `up` command via the `keypair` flag. We do support a `region` flag as well. E.g.:

`ecs-cli up --keypair test --capability-iam --cluster myCluster --region us-east-1`

Hope that helps!

**Comment by npsoni88** [comment]
I am positive hes aws-cli instance is likely using non-matching region. For example, the keys are created into us-east-1 while his current setup is using some other region. Check that with flag --region=us-east-1 (or wherever your keys are) and that should fix your problem.

**Comment by SoManyHs** [comment]
Hi @brainst0rm,

Let us know if you're still experiencing any issues -- I'll close this for now but feel free to open your problem isn't resolved. Thanks!
