### ISSUE TITLE
Mockgen Dep Complex

### ISSUE THREAD

**Issue by dickmao** [aws/amazon-ecs-cli#479]
### Summary
`make generate` in dev branch is not idempotent.  Results in `mockgen` failures.

### Description
Please consider vendoring `mockgen` and also removing mockgen generated files from git.

#478

**Comment by SoManyHs** [comment]
Hi @dickmao,
We realize there are some small idempotency issues with `make generate`, but these are usually remedied by running the command again. 

The [recommendation](https://blog.golang.org/generate) from the Go team is to commit generated files: ""Also, if the containing package is intended for import by go get, once the file is generated (and tested!) it must be checked into the source code repository to be available to clients." Since the mocks generated by `make generate` are necessary to run the tests, we also believe we should keep these files in git.

If you have specific failures that are continuing to be a problem, feel free to open a new issue that includes the failure output. Thank you!
