### ISSUE TITLE
Using the security group parameter does not work

### ISSUE THREAD

**Issue by mehmeta** [aws/amazon-ecs-cli#52]
If I specify a security group I created myself in a region like this:

ecs-cli up --keypair us-oregon  --capability-iam --size 1 --instance-type t2.small --azs us-west-2a,us-west-2b --security-group my-custom-group

my cluster creation never completes. Using the Cloudformation UI I can see that  the process got stuck at this stage:

22:32:58 UTC-0800	CREATE_IN_PROGRESS	AWS::AutoScaling::AutoScalingGroup	EcsInstanceAsg	Resource creation Initiated

**Comment by frewsxcv** [comment]
I can reproduce this error. In addition to the error described above by @mehmeta, if one looks at the autoscaling interface, one can see a bunch of instances failed to start with the error:

> The parameter SecurityGroup is not recognized

**Comment by ah903** [comment]
Have the same issue

**Comment by perryn** [comment]
We hit this too. Pretty bad that one of the documented parameters doesn't work at all.

**Comment by stilvoid** [comment]
Same here and it's the only way I can find to create an ECS cluster with more than one port open - which is pretty vital for anything other than a trivial web app.

**Comment by jestrada** [comment]
Did any of you solve this yet? I'm seeing the same issue. I also noticed that I can't add an inbound rule for an RDS security group for the security group created by ecs up.

**Comment by perryn** [comment]
@jestrada We dealt with it by allowing ecs-cli to create its own security group and then modifying that to match our requirements (although it sounds like you already tried that)

**Comment by jestrada** [comment]
Thanks for your comment @perryn , it motivated me to look into why the the security group wasn't showing up in the drop down when trying to enable access to the rds instance I have. After looking a little deeper, I figured out how to get it to work!

The issue we're seeing is caused by trying to assign a security group to a VPC it doesn't belong to. The default 'ecs-cli up' call will create a new VPC which can't access the security group you specify. To get this to work, add the --vpc and --subnets arguments for the vpc that owns the security group you're trying to use.

Enjoy! :dancer:

**Comment by dkjhanitt** [comment]
@jestrada 
Thanks a ton... Finally it worked for me.....  :+1:
