### ISSUE TITLE
Docs don't explain why --capability-iam is needed

### ISSUE THREAD

**Issue by mrichman** [aws/amazon-ecs-cli#579]
The documentation for `ecs-cli up ... --capability-iam` doesn't explain why the `--capability-iam` is needed. I believe it has something to do with the `ecsInstanceRole` IAM role that needs to exist, but I'm not certain. 

Please update the docs to elaborate on why the `--capability-iam` parameter is required (or when it might not be necessary).

Thanks!

**Comment by PettitWesley** [comment]
The flag `--capability-iam` exists because we use CloudFormation, and it corresponds with `CAPABILITY_IAM` in the [CloudFormation Docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html). It signifies an acknowledgment from the user that IAM resources will be created- the `ecsInstanceRole` that you mentioned. Since this role is only created with the `EC2` launch type, its not needed when are are using `FARGATE`.
