### ISSUE TITLE
Can't scale cluster: CloudFormation stack not found

### ISSUE THREAD

**Issue by mrichman** [aws/amazon-ecs-cli#580]
I'm trying to delete my cluster using `ecs-cli down` but it says that I must first terminate my running instances.

I attempted to do this using `ecs-cli scale --size 0 --cluster ECSCLI --capability-iam` where `ECSCLI` is the name of my cluster (and the name of my CF stack).

I get the following error, regardless of the value I specify for `--size`:

`FATA[0001] Error executing 'scale': CloudFormation stack not found for cluster 'ECSCLI'`

My CF stack does indeed exist in the same region.

**Comment by PettitWesley** [comment]
@mrichman try running `ecs-cli configure --cluster ECSCLI --region <your region> --cfn-stack-name ECSCLI` which will set the default cluster configuration for the CLI. You can later reference it in commands with `--cluster-config default`. This is needed because the CLI normally [adds a prefix](https://github.com/aws/amazon-ecs-cli/blob/master/ecs-cli/modules/config/command_config.go#L114) of `amazon-ecs-cli-setup-` to cluster name to create the template name. If you use a CFN stack that wasn't created by the CLI, then you need to configure its name.
