### ISSUE TITLE
ecs-cli compose service ps|list UnauthorizedOperation

### ISSUE THREAD

**Issue by arbazkhan002** [aws/amazon-ecs-cli#754]
### Summary
Using ecs-cli's compose service ps returns `UnauthorizedOperation: You are not authorized to perform this operation`

### Description

* Which specific command was run? 
` ecs-cli compose --project-name <name> --task-role-arn <arn> --file <docker-compose-file> --ecs-params <params-yml> service ps`
* Which version of the CLI you are using?
`1.13.1`
* Which version of Go are you using?
N/A
* What platform are you using to run ECS CLI commands?
Linux

### Observed Behavior
I used `ecs-cli compose service up` to bring up the service and all other ecs-cli compose service commands work fine except for `ps` or `list`. I tried setting broad IAM policies on the instance where I am running this and yet it gives the same output. 
#### Output
```WARN[0000] Skipping unsupported YAML option for service...  option name=build service name=<name>
WARN[0000] Skipping unsupported YAML option for service...  option name=stdin_open service name=<name>
FATA[0000] UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id:
```

#### Other commands work fine
```
$ ecs-cli compose --project-name <name> --task-role-arn <arn> --file <docker-compose-file> --ecs-params <params-yml> service scale 0
WARN[0000] Skipping unsupported YAML option for service...  option name=build service name=<name>
WARN[0000] Skipping unsupported YAML option for service...  option name=stdin_open service name=<name>
INFO[0000] Updated ECS service successfully              desiredCount=0 force-deployment=false service=<name>
INFO[0000] Service status                                desiredCount=0 runningCount=1 serviceName=<name>
```
#### IAM policy on the instance where I run ecs-cli
```
       {
            "Effect": "Allow",
            "Action": [
                "ecs:*"
            ],
            "Resource": "*",
            "Sid": "ECSFullAccess"
        }
```

What kind of IAM permissions are required to run ecs-cli compose service ps? I read [here](https://github.com/aws/amazon-ecs-cli/blob/master/ecs-cli/modules/commands/compose/service/compose_service_command.go#L37) that ECS.ListTasks is invoked with this command, but I believe it should be allowed given the above IAM policy. Something else I am missing?

**Comment by allisaurus** [comment]
Hi @arbazkhan002 - the `ps` command also makes up to 2 calls to EC2 ([DescribeInstances](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstances.html) and [DescribeNetworkInterfaces](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeNetworkInterfaces.html)) in order to display the IP addresses of the running tasks. If the IAM user executing the ecs-cli does not have permissions for these APIs, the operation will fail. 

If you can add permissions for these to your IAM policy, or attach the [AmazonEC2ReadOnlyAccess](https://console.aws.amazon.com/iam/home#policies/arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess)* manged policy to the ecs-cli user, then `ps` should succeed. Please let us know if that unblocks you. Thanks!

*links access requires signing into the AWS Console

**Comment by arbazkhan002** [comment]
Thanks @allisaurus , I added `"ec2:DescribeInstances"` to the IAM permissions and that seemed to be sufficient to execute `ps`. Is this already described in documentation somewhere? Thanks for helping me out anyway.
