### ISSUE TITLE
RequestError: send request failed

### ISSUE THREAD

**Issue by wicros** [aws/amazon-ecs-cli#778]
### Summary
It's normal to use the aws-cli. But when I use the ecs-cli with the same credentials it shows the errors below.

### Description
$ ecs-cli ps
FATA[0000] Error executing 'ps': RequestError: send request failed
caused by: Post https://ecs.ap-northeast-1.amazonaws.com/: dial tcp: lookup ecs.ap-northeast-1.amazonaws.com on [::1]:53: read udp [::1]:55158->[::1]:53: read: connection refused

$ ecs-cli up
ERRO[0000] Failed to Create Cluster                      cluster=linccluster error="RequestError: send request failed\ncaused by: Post https://ecs.ap-northeast-1.amazonaws.com/: dial tcp: lookup ecs.ap-northeast-1.amazonaws.com on [::1]:53: read udp [::1]:56846->[::1]:53: read: connection refused"
FATA[0000] Error executing 'up': RequestError: send request failed
caused by: Post https://ecs.ap-northeast-1.amazonaws.com/: dial tcp: lookup ecs.ap-northeast-1.amazonaws.com on [::1]:53: read udp [::1]:56846->[::1]:53: read: connection refused

**Comment by SoManyHs** [comment]
HI @wicros,

This error looks like you're having an issue with DNS lookup on your system, and not something specific to the ecs-cli. You might want to check your DNS settings or see if you are getting the same error on the aws cli. Closing this for now, since I don't think this is an ecs-cli issue, but feel free to re-open if you have more information. Thanks!

**Comment by LeifW** [comment]
I'm getting the same thing, on version 1.20.0 (7547c45).
Hitting that same URL w/ curl or my browser works, it just returns
```
<MissingAuthenticationTokenException>
  <Message>Missing Authentication Token</Message>
</MissingAuthenticationTokenException>
```
and the aws cli and java api client work fine for me w/ ECS.

**Comment by LeifW** [comment]
Turns out systemd-resolved is running on port 53. The ecs-cli error message seems to indicate port 53. Is ecs-cli running its own DNS server?
Anyway, after shutting down systemd-resolved, it works
https://unix.stackexchange.com/questions/304050/how-to-avoid-conflicts-between-dnsmasq-and-systemd-resolved
