### ISSUE TITLE
compose service up fails when the service already exists

### ISSUE THREAD

**Issue by raddevon** [aws/amazon-ecs-cli#93]
When I run the `compose up` command for an existing cluster, I get a timeout waiting for the existing tasks to come down.

```
WARN[0000] Skipping unsupported YAML option...           option name=restart
INFO[0000] Using ECS task definition                     TaskDefinition=ecscompose-ecs-test:16
INFO[0000] Updated the ECS service with a new task definition. Old containers will be stopped automatically, and replaced with new ones  desiredCount=1 serviceName=ecscompose-service-ecs-test taskDefinition=ecscompose-ecs-test:16
INFO[0000] Describe ECS Service status                   desiredCount=1 runningCount=1 serviceName=ecscompose-service-ecs-test
INFO[0030] Describe ECS Service status                   desiredCount=1 runningCount=1 serviceName=ecscompose-service-ecs-test
INFO[0060] Describe ECS Service status                   desiredCount=1 runningCount=1 serviceName=ecscompose-service-ecs-test
INFO[0090] Describe ECS Service status                   desiredCount=1 runningCount=1 serviceName=ecscompose-service-ecs-test
INFO[0120] Describe ECS Service status                   desiredCount=1 runningCount=1 serviceName=ecscompose-service-ecs-test
INFO[0150] Describe ECS Service status                   desiredCount=1 runningCount=1 serviceName=ecscompose-service-ecs-test
INFO[0180] Describe ECS Service status                   desiredCount=1 runningCount=1 serviceName=ecscompose-service-ecs-test
INFO[0210] Describe ECS Service status                   desiredCount=1 runningCount=1 serviceName=ecscompose-service-ecs-test
INFO[0240] Describe ECS Service status                   desiredCount=1 runningCount=1 serviceName=ecscompose-service-ecs-test
INFO[0270] Describe ECS Service status                   desiredCount=1 runningCount=1 serviceName=ecscompose-service-ecs-test
INFO[0300] Describe ECS Service status                   desiredCount=1 runningCount=1 serviceName=ecscompose-service-ecs-test
INFO[0330] Describe ECS Service status                   desiredCount=1 runningCount=1 serviceName=ecscompose-service-ecs-test
INFO[0360] Describe ECS Service status                   desiredCount=1 runningCount=1 serviceName=ecscompose-service-ecs-test
INFO[0390] Describe ECS Service status                   desiredCount=1 runningCount=1 serviceName=ecscompose-service-ecs-test
INFO[0420] Describe ECS Service status                   desiredCount=1 runningCount=1 serviceName=ecscompose-service-ecs-test
INFO[0450] Describe ECS Service status                   desiredCount=1 runningCount=1 serviceName=ecscompose-service-ecs-test
INFO[0481] Describe ECS Service status                   desiredCount=1 runningCount=1 serviceName=ecscompose-service-ecs-test
INFO[0511] Describe ECS Service status                   desiredCount=1 runningCount=1 serviceName=ecscompose-service-ecs-test
INFO[0541] Describe ECS Service status                   desiredCount=1 runningCount=1 serviceName=ecscompose-service-ecs-test
INFO[0571] Describe ECS Service status                   desiredCount=1 runningCount=1 serviceName=ecscompose-service-ecs-test
FATA[0601] Timeout waiting for service ecscompose-service-ecs-test to get stable
```

I found [what may be a related ticket on the ecs-agent repo](https://github.com/aws/amazon-ecs-agent/issues/339) which suggests the problem may be with agent 1.8.0. Can I somehow make the CLI install the 1.8.1 agent?

**Comment by raddevon** [comment]
Same result after manually updating the agent on the instance and verifying it is now running 1.8.1 via the web console. I seem to have misdiagnosed the issue as a problem with an older version of the ECS agent. Any suggestions for how to fix this?

**Comment by ilg** [comment]
If, in the web console, you go into the service and look at the Events tab, do you see something like:

> service _[service name]_ was unable to place a task because no container instance met all of its requirements. The closest matching container-instance _[instance id]_ is already using a port required by your task. For more information, see the Troubleshooting section.

I'm curious because that's what I'm seeing right now and I'm trying to figure out what to do about it.

**Comment by uttarasridhar** [comment]
Each service is configured with deployment parameters. For more details, you can read [the docs](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/service_definition_paramters.html).

One of the deployment parameters is minimumHealthyPercent, which is the percent of desired tasks that must remain running in a service during a deployment. Before v0.3.0, ecs-cli also configured this to be a default of **100%** (With the release of [v0.3.0](https://github.com/aws/amazon-ecs-cli/releases/tag/v0.3.0), this field is configurable in `ecs-cli compose service create/up/scale` commands).

If the minimumHealthyPercent is 100%, then you would **need idle capacity** to launch 1 more task before it can stop the old one.

And looking at the error, "was unable to place a task because no container instance met all of its requirements." and "is already using a port", it shows that the task definition has a static port x which is occupied by EC2 instance(s) in that cluster. So you can either, scale up your cluster by adding a new container instance OR you can update the service with less strict minimum healthy percent (using the ecs-cli, you will need to run `ecs-cli compose service up --deployment-min-healthy-percent 80` Refer to [our docs](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose-service.html) for more details.)

**Comment by uttarasridhar** [comment]
Let us know by re-opening the issue if you are still running into issues.
