### ISSUE TITLE
dep Gopkg.toml Gopkg.lock, and vendor dependencies not in tight sync

### ISSUE THREAD

**Issue by diablodale** [aws/amazon-ecs-cli#978]
Files checked into this repo in the `vendor` directory are not in tight sync with `Gopkg.toml`. In addition, `Gopkg.toml` and `Gopkg.lock` may not be in sync with each other. (Caveat, I am newish to go and dep...and SemVer ranges are involved...so perhaps there is something I have misunderstood.)

### Description

To start, two examples that expose the out-of-sync, or my lack of understanding 😉

#### `Gopkg.toml` and `Gopkg.lock` out of sync with each other

Reference the `version` value in

https://github.com/aws/amazon-ecs-cli/blob/d1685dd9bbd4e3d9375a7e076f69cc20ec64c13b/ecs-cli/Gopkg.toml#L79-L81

and now in

https://github.com/aws/amazon-ecs-cli/blob/d1685dd9bbd4e3d9375a7e076f69cc20ec64c13b/ecs-cli/Gopkg.lock#L126-L139

They do not match. However, due to SemVer (see Notes below) this may be technically possible. However, is this desired? Does the team actually want any (version >18.6.0) but not the 19.x.x updates? 🤔 Or perhaps someone didn't realize how dep's resolver would work here.

#### `vendor/` files out of sync with `Gopkg.*`

Next, look at the contents of the following file from that `github.com/docker/cli` dependency. `Gopkg.toml` declares that this dependency should be tag `18.06.0-ce` or greater in the 18.x.x range. Here is a specific line of a file in that dependency at that tag

https://github.com/docker/cli/blob/2cb2e84287c916d484cf5d6fc93987ba537f3aab/cli/compose/loader/loader.go#L268

```go
func transform(source map[string]interface{}, target interface{}) error {
```

Now compare that line to the file currently checked into the `vendor/` directory

https://github.com/aws/amazon-ecs-cli/blob/d1685dd9bbd4e3d9375a7e076f69cc20ec64c13b/ecs-cli/vendor/github.com/docker/cli/cli/compose/loader/loader.go#L270

As you can see, these are different files. The file checked into `vendor` does not match the dependency declaration. Instead, that file is something newer than tag `18.06.0-ce`.

### Notes

I see activity by two people on or arounds these dep file entries and this specific dependency. They may have some knowledge: @efekarakus and @allisaurus

Perhaps contributing to this, is how constraints have been declared in `Gopkg.toml`. There are several that are not frozen at a specific version and instead will update to whatever is the latest version using dep and SemVer rules. For example, the dependency above is declared

https://github.com/aws/amazon-ecs-cli/blob/d1685dd9bbd4e3d9375a7e076f69cc20ec64c13b/ecs-cli/Gopkg.toml#L79-L81

Because of the dep and SemVer rules, `version = "18.06.0-ce"` is made into a canonical constraint `^18.6.0-ce`. Correct. It drops the `0` and prepends the `^`. The caret pins the left-most non-zero digit in the constraint. So in this case, it means: (version >= 18.6.0) and (version < 19.0.0). I tested and that constraint on that dependency installed `docker/cli` tag `v18.09.9`. 🤹‍♀️

If it is desired to have a specific tag and nothing newer, then the constraint should be either `version = "=18.06.0-ce"` or `revision = "v18.06.0-ce"`

Using this method and some hunting, I determined that the files checked into `vendor/` are **not** from the newest possible with the current constraint. Instead, they are likely from tag `v18.09.5`. That suggests that someone manually copied files (hope not) or ran `dep ensure -update github.com/docker/cli` in the period of time that `v18.09.5` was the newest. If this command was run today, it would pull `v18.09.9` which has different files.

**Comment by PettitWesley** [comment]
Removing the bug label since this doesn't impact users of any CLI release.

@diablodale We're not experts in go dep (in most of our other projects we use go modules). 

If this is causing issues for you as you develop CLI features, feel free to submit a PR to fix/change it.  As far as constraints go, in general we prefer to use the latest version of dependencies, unless backwards breaking changes force us to stick with an older version. 

Specifically for the docker dependency, I'm not sure if there was a reason why we tried to pin the CLI to a specific version. 

CC @allisaurus for further comment.

**Comment by allisaurus** [comment]
@diablodale I agree the ambiguity of `version = "18.06.0-ce"` (vs `version = "=18.06.0-ce`" or `revision = "v18.06.0-ce"`) is confusing, and we should pin to specific revision correctly or explicitly allow for later minor versions (with `^`). Some of the constraints in `Gopkg.toml` are indeed using `"=x.x.x"` and that would be my preference for keeping `/vendor` more consistent but I'll confer with others who've had their hand in here before overhauling the lot.

Per @PettitWesley 's comment, if this has become a blocker for you and you're willing to submit a PR which pins this constraint to the version you believe is actually present in `/vendor`, please do! A PR dedicated to such a change is a good venue to test & discuss it. Otherwise, we'll regroup and submit a more general `dep`/`Gopkg.toml` overhaul after confirming how we need to proceed. Thanks for bringing this to our attention!

**Comment by diablodale** [comment]
Got it. Then I will submit a PR that pins the `github.com/docker/cli` dependency. More detail and discussion on specifics there.
