### ISSUE TITLE
Running my ecs-cluster containers locally

### ISSUE THREAD

**Issue by saifabuhashish** [aws/amazon-ecs-cli#983]
Hi!
I am using the ecs-cli local tool to run my containers locally, however I am having a hard time figuring out the network they're running in. How would I be able to test these containers, i.e. make sure theyre actually running by hitting their endpoints? Are they running on localhost? I checked the generated docker-compose file and it said `null` under `ecs-local-network`. Your help is much appreciated.

**Comment by PettitWesley** [comment]
@saifabuhashish You containers will use a [user defined bridge network](https://github.com/awslabs/amazon-ecs-local-container-endpoints/blob/master/docs/setup-networking.md#option-1-use-a-user-defined-docker-bridge-network-recommended)

You can find the local IP that your container is given with docker inspect:

```
docker inspect -f '{{ .NetworkSettings.IPAddress }}' {container ID}
```

You can than hit that IP with curl (make sure you use the right port for your app) and you should get a response.

To see the docker networks, you can run `docker network ls`. 

Alternatively, if you add a port mapping for your container, then when you test it locally that port will be exposed on localhost instead of an alternate private IP.

Let me know if you need more help!

**Comment by saifabuhashish** [comment]
Where do I add that port mapping for my container?

**Comment by iamhopaul123** [comment]
@saifabuhashish you can define it in your task def file.

**Comment by efekarakus** [comment]
Resolving this issue, please feel free to re-open it if the instructions were not clear :)
